project:
  type: website
  output-dir: docs

website:
  title: "Christian Schwaderer"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: research.qmd
        text: Research
      - href: teaching.qmd
        text: Teaching
      - href: Contact.qmd
        text: Contact
      - href: Publications.qmd
        text: Publications
    right:
      - icon: github
        href: https://github.com/christianschwaderer
      - icon: twitter-x
        href: https://x.com/ChristianSchwad
      - icon: google
        href: https://scholar.google.com/citations?user=Q6ZDrAYAAAAJ&hl=en&authuser=1
      - icon: envelope
        href: "mailto:christian.schwaderer@uibk.ac.at"
      - icon: bank
        href: https://www.uibk.ac.at/en/politikwissenschaft/institut/team/

format:
  html:
    theme: lux # You can change the theme to another Bootswatch theme
    css: styles.css # Optional: Add custom CSS
    include-in-header:
      - text: |
          <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons/font/bootstrap-icons.css">
          <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/academicons/1.8.6/css/academicons.min.css">

